### ISSUE TITLE
Functional and component specification feedback

### ISSUE THREAD

**Issue by elmisback** [lindseyulmer/Voting-COVID#1]
* Functional
    * https://github.com/lindseyulmer/Voting-COVID/blob/main/docs/Functional_Specification.md
    * Problem being addressed
        * Visualize COVID-19 and election data in the same place
    * Data sources, data structure
        * Covid data + variety of voting data
    * Users: domain, skills, programming experience
        * Anyone; "should be comfortable using a Jupyter notebook to generate map figures"
            * Somewhat steep requirement?
        * (Looks like there's also a use case for non-programmers)
    * At least 2 use cases
        * "I want to create a map with the existing data"
        * "I want to add my data to the map"
        * "I want to look at a pre-generated map with the existing data"
* Component
    * https://github.com/lindseyulmer/Voting-COVID/blob/main/docs/Component_Specification.md
    * 3+ software components: what it does, inputs it requires, and outputs it provides.
        * What are the parts of the application and how do they interact with each other? Try drawing a diagram that explains for a specific use case how data moves through the parts of your application and what is shown to the user.
        * make_plot is use case 1
        * add_data serves use case 2
        * interaction component is unclear
    * Preliminary plan
        * Focus on getting a minimal setup working first, then add more data and features if you have time.

**Comment by cyac15** [comment]
We've redesigned our functions and components.
